### ISSUE TITLE
`poetry add syncthing` is failing

### ISSUE THREAD

**Issue by savil** [blakev/python-syncthing#30]
Hello, thank you for making `python syncthing`! I'm trying it out , but running into the following error with doing `poetry add syncthing`.  You should be able to try it out at https://repl.it/repls/EntirePaleSystemresource#main.py (be sure to press the PLAY button!).

Have you encountered this before? Any idea how to get around it?

```
--> python3 -m poetry add syncthing
Using version ^2.4.2 for syncthing

Updating dependencies
Resolving dependencies...

Writing lock file


Package operations: 3 installs, 3 updates, 0 removals

  - Updating idna (2.9 -> 2.10)
  - Installing pytzdata (2020.1)
  - Updating urllib3 (1.25.9 -> 1.25.10)
  - Installing pendulum (2.1.2)
  - Updating yarl (1.4.2 -> 1.5.1)
  - Installing syncthing (2.4.2)

[EnvCommandError]
Command ['/opt/virtualenvs/python3/bin/pip', 'install', '--no-deps', 'syncthing==2.4.2'] errored with the following return code 1, and output: 
Collecting syncthing==2.4.2
  Downloading syncthing-2.4.2.tar.gz (12 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /opt/virtualenvs/python3/bin/python3 /opt/virtualenvs/python3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpq_a01jr9
         cwd: /tmp/pip-install-a4jmpbst/syncthing
    Complete output (16 lines):
    Traceback (most recent call last):
      File "/opt/virtualenvs/python3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/opt/virtualenvs/python3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/opt/virtualenvs/python3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-7j243us7/overlay/lib/python3.8/site-packages/poetry/masonry/api.py", line 39, in prepare_metadata_for_build_wheel
        builder = WheelBuilder(poetry, SystemEnv(Path(sys.prefix)), NullIO())
      File "/tmp/pip-build-env-7j243us7/overlay/lib/python3.8/site-packages/poetry/masonry/builders/wheel.py", line 44, in __init__
        super(WheelBuilder, self).__init__(poetry, env, io)
      File "/tmp/pip-build-env-7j243us7/overlay/lib/python3.8/site-packages/poetry/masonry/builders/builder.py", line 65, in __init__
        self._module = Module(
      File "/tmp/pip-build-env-7j243us7/overlay/lib/python3.8/site-packages/poetry/masonry/utils/module.py", line 58, in __init__
        raise ModuleOrPackageNotFound(
    poetry.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package python-syncthing
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/virtualenvs/python3/bin/python3 /opt/virtualenvs/python3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpq_a01jr9 Check the logs for full command output.
WARNING: You are using pip version 20.1.1; however, version 20.2.2 is available.
You should consider upgrading via the '/opt/virtualenvs/python3/bin/python3 -m pip install --upgrade pip' command.

exit status 1

```

**Comment by blakev** [comment]
Weird...I will look into this this weekend, thanks!

I use poetry so I'm familiar with its quirks, hopefully I can figure it out.

**Comment by Maigre** [comment]
Got the same error on RPi Arch armv7 when executing `pip install syncthing`
it works well with `pip install 'syncthing==2.4.1'`

Best,
Thomas
