### ISSUE TITLE
Fails with Python 3.9?

### ISSUE THREAD

**Issue by pedrojvaz** [blakev/python-syncthing#32]
```
> pip3 install syncthing
Collecting syncthing
  Downloading syncthing-2.4.2.tar.gz (12 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/x5/fhclz7wd19168qv2gp61fpm40000gn/T/tmpr7rltjfk
         cwd: /private/var/folders/x5/fhclz7wd19168qv2gp61fpm40000gn/T/pip-install-8goti_9c/syncthing
    Complete output (16 lines):
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/private/var/folders/x5/fhclz7wd19168qv2gp61fpm40000gn/T/pip-build-env-52j602e6/overlay/lib/python3.9/site-packages/poetry/core/masonry/api.py", line 35, in prepare_metadata_for_build_wheel
        builder = WheelBuilder(poetry)
      File "/private/var/folders/x5/fhclz7wd19168qv2gp61fpm40000gn/T/pip-build-env-52j602e6/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py", line 46, in __init__
        super(WheelBuilder, self).__init__(poetry, executable=executable)
      File "/private/var/folders/x5/fhclz7wd19168qv2gp61fpm40000gn/T/pip-build-env-52j602e6/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/builder.py", line 82, in __init__
        self._module = Module(
      File "/private/var/folders/x5/fhclz7wd19168qv2gp61fpm40000gn/T/pip-build-env-52j602e6/overlay/lib/python3.9/site-packages/poetry/core/masonry/utils/module.py", line 58, in __init__
        raise ModuleOrPackageNotFound(
    poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package python-syncthing
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/x5/fhclz7wd19168qv2gp61fpm40000gn/T/tmpr7rltjfk Check the logs for full command output.
```

**Comment by w-ns** [comment]
I've got the same bug. Using 2.4.1 as workaround worked for me: pip3 install 'syncthing==2.4.1'
Maybe this is related to #30 ?

Best regards and thanks for this quite useful software.
