### ISSUE TITLE
Getting an error on install

### ISSUE THREAD

**Issue by mattalxndr** [blakev/python-syncthing#38]
This is the error I get when I try to install this:

```
(.venv) syncthing % pip install -r requirements.txt
Collecting syncthing (from -r requirements.txt (line 1))
Using cached syncthing-2.4.2.tar.gz (12 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing metadata (pyproject.toml) ... error
error: subprocess-exited-with-error

× Preparing metadata (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [20 lines of output]
Traceback (most recent call last):
File "/home/**/Projects/home/syncthing/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
main()
File "/home/**/Projects/home/syncthing/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/**/Projects/home/syncthing/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
return hook(metadata_directory, config_settings)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/pip-build-env-uk_kdgzt/overlay/lib/python3.11/site-packages/poetry/core/masonry/api.py", line 42, in prepare_metadata_for_build_wheel
builder = WheelBuilder(poetry)
^^^^^^^^^^^^^^^^^^^^
File "/tmp/pip-build-env-uk_kdgzt/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/wheel.py", line 61, in __init__
super().__init__(poetry, executable=executable)
File "/tmp/pip-build-env-uk_kdgzt/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/builder.py", line 85, in __init__
self._module = Module(
^^^^^^^
File "/tmp/pip-build-env-uk_kdgzt/overlay/lib/python3.11/site-packages/poetry/core/masonry/utils/module.py", line 69, in __init__
raise ModuleOrPackageNotFound(
poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package python-syncthing
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
pip install -r requirements.txt  6.42s user 0.32s system 75% cpu 8.911 total
```

```
% cat requirements.txt
syncthing
% ./.venv/bin/python --version
Python 3.11.4
% uname -a
Linux m 6.5.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 06 Sep 2023 21:01:01 +0000 x86_64 GNU/Linux
```

Thanks

**Comment by VideoFX** [comment]
I also get this error when installing on python 3.8 windows.
