### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by techtonik** [blakev/python-syncthing#4]
```
$ python -m syncthing
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib/python2.7/runpy.py", line 109, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "/usr/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/usr/local/lib/python2.7/dist-packages/syncthing/__init__.py", line 10, in <module>
    from .syncthing import Syncthing
  File "/usr/local/lib/python2.7/dist-packages/syncthing/syncthing.py", line 100, in <module>
    class Syncthing(with_metaclass(SyncthingType, object)):
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 778, in __new__
    return meta(name, bases, d)
  File "/usr/local/lib/python2.7/dist-packages/syncthing/syncthing.py", line 58, in __init__
    ins_file = get_latest_documentation()
  File "/usr/local/lib/python2.7/dist-packages/syncthing/interface.py", line 42, in get_latest_documentation
    os.makedirs(cache_folder)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/syncthing/docs'
```
Why it needs to download documentation?

**Comment by blakev** [comment]
It shouldn't. I'll look into this today -- I included the documentation from the latest release, but must have done something wrong.

**Comment by blakev** [comment]
This is fixed now that python-syncthing doesn't rely on external files.
